name: finanflow
description: FinanFlow — App de finanças pessoais
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Estado
  provider: ^6.1.2

  # Banco de dados local
  sqflite: ^2.3.3+1
  sqflite_common_ffi: ^2.3.3
  sqflite_common_ffi_web: ^0.4.2+3
  path: ^1.9.0

  # UI e fontes
  google_fonts: ^6.2.1
  fl_chart: ^0.69.0

  # Utilitários
  intl: ^0.20.2
  uuid: ^4.4.0
  shared_preferences: ^2.3.2
  crypto: ^3.0.3          # hash de senha (SHA-256 + salt)
  path_provider: ^2.1.0   # diretório para salvar o CSV exportado
  share_plus: ^10.0.0     # compartilhar o arquivo CSV
  image_picker: ^1.1.2   # selecionar foto de perfil da câmera/galeria

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
